name: Alerte iPhone toutes les heures

on:
  schedule:
    - cron: '0 * * * *'  # toutes les heures pile
  workflow_dispatch:     # pour lancer manuellement

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Google Chrome
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb

    - name: Setup Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install undetected_chromedriver selenium requests

    - name: Run script
      run: python alerte_iphone.py
